services:
  storefront:
    build: .
    networks:
      shopnet:
        ipv4_address: 172.28.0.10
    ports:
      - "8000:8000"

networks:
  shopnet:
    ipam:
      config:
        - subnet: 172.28.0.0/16
